export const ACCESS_KEY_GENERATION_KEY='jflkdjlaeoslfdsklfjsklfjdlkfjsfkldsjflksjfslkfjdklfsjflkdsjflk39029290dkldsklfjsklfjflkdjfdlksfjdlskfjdslkfjdslkfjdflkfjslkfjlk'
export const SECRET_KEY_FOR_EMAIL_ENCRYPTION='jflkdjlaeoslfdsklfjsklfjdlkfjsfkldsjflksjfslkfjdklfsjflkdsjflk39029290dkldsklf'
