/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 tlight.gltf --transform
Author: urbanmasque (https://sketchfab.com/urbanmasque)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/traffic-light-9db89a2de2a4463d9d5b48486cdb3fc7
Title: Traffic Light
*/

import { useGLTF } from '@react-three/drei'

export default function Model(props: any) {
  const { nodes, materials}: any = useGLTF('/tlight-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.46}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.Layer_1__0.geometry} material={materials['Scene_-_Root']} />
          <mesh geometry={nodes.Layer_2__0.geometry} material={materials['Scene_-_Root']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tlight-transformed.glb')
